CREATE TABLE `CAR` (
	`CAR_PK`	VARCHAR(20)	NOT NULL,
	`COMPANY_FK`	VARCHAR(20)	NOT NULL,
	`CAR_NAME`	VARCHAR(20)	NULL,
	`CAR_YEAR`	VARCHAR(20)	NULL
);

CREATE TABLE `COMPANY` (
	`COMPANY_PK`	VARCHAR(20)	NOT NULL,
	`COMPANY_NAME`	VARCHAR(20)	NULL
);

CREATE TABLE `CAROPTION` (
	`OPTION_PK`	VARCHAR(20)	NOT NULL,
	`CAR_FK`	VARCHAR(20)	NOT NULL,
	`COMPANY_FK`	VARCHAR(20)	NOT NULL,
	`OPTION_NAME`	VARCHAR(300)	NULL
);

ALTER TABLE `CAR` ADD CONSTRAINT `PK_CAR` PRIMARY KEY (
	`CAR_PK`,
	`COMPANY_FK`
);

ALTER TABLE `COMPANY` ADD CONSTRAINT `PK_COMPANY` PRIMARY KEY (
	`COMPANY_PK`
);

ALTER TABLE `CAROPTION` ADD CONSTRAINT `PK_CAROPTION` PRIMARY KEY (
	`OPTION_PK`,
	`CAR_FK`,
	`COMPANY_FK`
);

ALTER TABLE `CAR` ADD CONSTRAINT `FK_COMPANY_TO_CAR_1` FOREIGN KEY (
	`COMPANY_FK`
)
REFERENCES `COMPANY` (
	`COMPANY_PK`
);

ALTER TABLE `CAROPTION` ADD CONSTRAINT `FK_CAR_TO_CAROPTION_1` FOREIGN KEY (
	`CAR_FK`
)
REFERENCES `CAR` (
	`CAR_PK`
);

ALTER TABLE `CAROPTION` ADD CONSTRAINT `FK_CAR_TO_CAROPTION_2` FOREIGN KEY (
	`COMPANY_FK`
)
REFERENCES `CAR` (
	`COMPANY_FK`
);

